# Generated by Django 5.2.4 on 2025-07-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="grade_level",
            field=models.CharField(
                choices=[
                    ("freshman", "Freshman"),
                    ("sophomore", "Sophomore"),
                    ("junior", "Junior"),
                    ("senior", "Senior"),
                    ("general", "General"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userschedule",
            name="semester",
            field=models.CharField(
                choices=[("fall", "Fall"), ("spring", "Spring"), ("summer", "Summer")],
                max_length=20,
            ),
        ),
    ]
